version: 2

models:
  - name: mrt_order_daily_report
    description: This table contains informations about orders for reporting at daily level
       

    columns:
      - name: report_date
        description: This is the date of orders