version: 2

models:
  - name: stg_sales_database__order
    description: This table contains informations about orders
       

    columns:
      - name: order_id
        description: This is a unique identifier for the order
        tests:
        - not_null
        - unique

  - name: stg_sales_database__order_item
    description: This table contains informations about orders

    columns:
      - name: order_item_id
        description: This is a unique identifier for the order item level

  - name: stg_sales_database__customer
    description: This table contains informations about customers

    columns:
      - name: customer_id
        description: This is a unique identifier for the customer

  - name: stg_sales_database__feedback
    description: This table contains informations about feedbacks

    columns:
      - name: feedback_id
        description: This is a unique identifier for the feedback

  - name: stg_sales_database__payment
    description: This table contains informations about payments

    columns:
      - name: payment_id
        description: This is a unique identifier for the payments

  - name: stg_sales_database__product
    description: This table contains informations about products

    columns:
      - name: product_id
        description: This is a unique identifier for the products

  - name: stg_sales_database__seller
    description: This table contains informations about sellers

    columns:
      - name: seller_id
        description: This is a unique identifier for the seller
