version: 2

sources:
  - name: google_analytics_4
    schema: google_analytics_4
    tables:
      - name: events_20210131
      - name : events_flattened
      - name : events_flattened_clustered
      
  - name: googles_sheets
    schema: googles_sheets
    tables:
      - name: account_manager_region_mapping
      - name : marketing_budget

  - name: sales_database
    schema: sales_database
    tables:
      - name: feedback
      - name: payment
      - name: product
      - name: order
      - name: order_item
      - name: seller
      - name: user

  - name: spotify
    schema: spotify
    tables:
      - name: songs
      - name : listening_data